repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.2.1"
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
  #- repo: https://github.com/pycqa/bandit
  #  rev: 1.7.4
  #  hooks:
  #  - id: bandit
  #    exclude: tests/
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        args: [--ignore, "40459,43041,44423,44426,44427,44741,44742,48040,48041,49733,50454,51340,52945,55264,53315,59293,60956,61586,62126,64976,65771,72095,72109,72110,72111,72515,72520,72521,73023,73028"] # ignoring Django vulnerability IDs
